services:
  - type: web
    name: agileboard-backend
    plan: free
    buildCommand: ./mvnw clean install
    startCommand: java -Dserver.port=$PORT -jar target/*.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://aws-0-us-east-2.pooler.supabase.com:6543/postgres
      - key: SPRING_DATASOURCE_USERNAME
        value: postgres.sgxolbycxcjkluumqwqn
      - key: SPRING_DATASOURCE_PASSWORD
        value: 1234
      - key: PORT
        value: 8080
